<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;

class CropSeeder extends Seeder
{
    public function run(): void
    {
        $crops = [
            [
                'name' => 'Tomato',
                'scientific_name' => 'Solanum lycopersicum',
                'category' => 'Vegetable',
                'recommended_ph' => 6.20,
                'recommended_ph_min' => 6.0,
                'recommended_ph_max' => 6.8,
                'recommended_water' => 400.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Daily or every 2 days',
                'water_requirement_liters_per_hectare' => 40000.00,
                'growth_period_days' => 80,
                'temperature_min' => 18.0,
                'temperature_max' => 29.0,
                'humidity_min' => 65.0,
                'humidity_max' => 85.0,
                'wind_min' => 1.0,
                'wind_max' => 4.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Tomatoes require consistent moisture. Irregular watering causes blossom end rot and fruit cracking. Mulching helps maintain soil moisture.',
            ],
            [
                'name' => 'Potato',
                'scientific_name' => 'Solanum tuberosum',
                'category' => 'Root Vegetable',
                'recommended_ph' => 5.50,
                'recommended_ph_min' => 5.0,
                'recommended_ph_max' => 6.0,
                'recommended_water' => 500.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Every 2-3 days',
                'water_requirement_liters_per_hectare' => 50000.00,
                'growth_period_days' => 120,
                'temperature_min' => 15.0,
                'temperature_max' => 22.0,
                'humidity_min' => 60.0,
                'humidity_max' => 80.0,
                'wind_min' => 0.5,
                'wind_max' => 4.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Potatoes perform best in cool conditions. Consistent moisture during tuber formation is critical. Avoid waterlogging which causes tuber rot.',
            ],
            [
                'name' => 'Olive',
                'scientific_name' => 'Olea europaea',
                'category' => 'Tree Fruit',
                'recommended_ph' => 7.00,
                'recommended_ph_min' => 6.5,
                'recommended_ph_max' => 7.5,
                'recommended_water' => 300.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Weekly or every 10 days',
                'water_requirement_liters_per_hectare' => 30000.00,
                'growth_period_days' => 180,
                'temperature_min' => 10.0,
                'temperature_max' => 35.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'wind_min' => 1.0,
                'wind_max' => 6.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Olives are drought-tolerant but produce better yields with moderate irrigation. They thrive in Mediterranean climates with hot dry summers.',
            ],
            [
                'name' => 'Corn',
                'scientific_name' => 'Zea mays',
                'category' => 'Cereal Grain',
                'recommended_ph' => 6.00,
                'recommended_ph_min' => 5.8,
                'recommended_ph_max' => 6.8,
                'recommended_water' => 600.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Every 2-3 days during growing season',
                'water_requirement_liters_per_hectare' => 60000.00,
                'growth_period_days' => 100,
                'temperature_min' => 18.0,
                'temperature_max' => 32.0,
                'humidity_min' => 50.0,
                'humidity_max' => 80.0,
                'wind_min' => 1.0,
                'wind_max' => 5.0,
                'recommended_device' => 'WaterWind Pro',
                'notes' => 'Corn has high water demands, especially during tasseling and silking. Critical water period is 2 weeks before to 3 weeks after tasseling.',
            ],
            [
                'name' => 'Wheat',
                'scientific_name' => 'Triticum aestivum',
                'category' => 'Cereal Grain',
                'recommended_ph' => 6.50,
                'recommended_ph_min' => 6.0,
                'recommended_ph_max' => 7.0,
                'recommended_water' => 450.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Weekly during dry periods',
                'water_requirement_liters_per_hectare' => 45000.00,
                'growth_period_days' => 120,
                'temperature_min' => 10.0,
                'temperature_max' => 25.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'wind_min' => 1.0,
                'wind_max' => 5.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Wheat is moderately drought-tolerant. Most water-sensitive stages are tillering and grain filling. Excessive moisture can promote fungal diseases.',
            ],
            [
                'name' => 'Rice',
                'scientific_name' => 'Oryza sativa',
                'category' => 'Cereal Grain',
                'recommended_ph' => 6.00,
                'recommended_ph_min' => 5.5,
                'recommended_ph_max' => 6.5,
                'recommended_water' => 1200.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Continuous flooding or alternate wetting and drying',
                'water_requirement_liters_per_hectare' => 120000.00,
                'growth_period_days' => 150,
                'temperature_min' => 20.0,
                'temperature_max' => 35.0,
                'humidity_min' => 70.0,
                'humidity_max' => 90.0,
                'wind_min' => 0.0,
                'wind_max' => 3.0,
                'recommended_device' => 'WaterWind Pro',
                'notes' => 'Rice is the most water-intensive cereal crop. Paddy fields require standing water. Alternate wetting and drying can reduce water use by 30% without yield loss.',
            ],
            [
                'name' => 'Cotton',
                'scientific_name' => 'Gossypium hirsutum',
                'category' => 'Fiber Crop',
                'recommended_ph' => 6.50,
                'recommended_ph_min' => 5.8,
                'recommended_ph_max' => 7.0,
                'recommended_water' => 700.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Every 7-10 days',
                'water_requirement_liters_per_hectare' => 70000.00,
                'growth_period_days' => 150,
                'temperature_min' => 20.0,
                'temperature_max' => 35.0,
                'humidity_min' => 40.0,
                'humidity_max' => 75.0,
                'wind_min' => 1.0,
                'wind_max' => 5.0,
                'recommended_device' => 'WaterWind Pro',
                'notes' => 'Cotton requires warm temperatures and moderate water. Excess water during boll opening reduces fiber quality. Deficit irrigation can be used strategically.',
            ],
            [
                'name' => 'Sunflower',
                'scientific_name' => 'Helianthus annuus',
                'category' => 'Oilseed Crop',
                'recommended_ph' => 6.50,
                'recommended_ph_min' => 6.0,
                'recommended_ph_max' => 7.0,
                'recommended_water' => 400.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Every 7-10 days',
                'water_requirement_liters_per_hectare' => 40000.00,
                'growth_period_days' => 90,
                'temperature_min' => 18.0,
                'temperature_max' => 33.0,
                'humidity_min' => 40.0,
                'humidity_max' => 75.0,
                'wind_min' => 1.0,
                'wind_max' => 5.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Sunflowers are moderately drought-tolerant due to deep root systems. Critical water period is during flowering and seed filling stages.',
            ],
            [
                'name' => 'Barley',
                'scientific_name' => 'Hordeum vulgare',
                'category' => 'Cereal Grain',
                'recommended_ph' => 6.50,
                'recommended_ph_min' => 6.0,
                'recommended_ph_max' => 7.5,
                'recommended_water' => 380.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Weekly during dry spells',
                'water_requirement_liters_per_hectare' => 38000.00,
                'growth_period_days' => 90,
                'temperature_min' => 12.0,
                'temperature_max' => 25.0,
                'humidity_min' => 35.0,
                'humidity_max' => 70.0,
                'wind_min' => 1.0,
                'wind_max' => 6.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Barley is one of the most drought-tolerant cereal crops. It can survive on minimal rainfall and is ideal for arid and semi-arid regions.',
            ],
            [
                'name' => 'Grapes',
                'scientific_name' => 'Vitis vinifera',
                'category' => 'Fruit Crop',
                'recommended_ph' => 6.00,
                'recommended_ph_min' => 5.5,
                'recommended_ph_max' => 7.0,
                'recommended_water' => 350.00,
                'recommended_water_type' => 'Fresh Water',
                'irrigation_frequency' => 'Every 7-14 days depending on stage',
                'water_requirement_liters_per_hectare' => 35000.00,
                'growth_period_days' => 160,
                'temperature_min' => 15.0,
                'temperature_max' => 35.0,
                'humidity_min' => 40.0,
                'humidity_max' => 70.0,
                'wind_min' => 1.0,
                'wind_max' => 5.0,
                'recommended_device' => 'WaterWind Micro',
                'notes' => 'Grapes benefit from controlled water stress during ripening to concentrate flavors. Excessive humidity promotes fungal diseases like powdery mildew.',
            ],
        ];

        foreach ($crops as $crop) {
            Crop::create($crop);
        }
    }
}
