<?php

namespace Database\Seeders;

use App\Models\Soil;
use Illuminate\Database\Seeder;

class SoilSeeder extends Seeder
{
    public function run(): void
    {
        $soils = [
            [
                'name' => 'Sandy',
                'soil_texture' => 'Coarse',
                'water_retention' => 15.00,
                'drainage' => 95.00,
                'organic_matter' => 1.50,
                'fertility' => 'Low',
                'salinity' => 2.00,
                'ph_min' => 5.5,
                'ph_max' => 7.0,
                'recommended_crops' => 'Olive, Potato, Watermelon, Carrot, Peanut',
                'description' => 'Sandy soil has large particles and drains very quickly. It retains little water and nutrients, requiring frequent irrigation.',
                'notes' => 'Best suited for drought-tolerant and root crops. Benefits from organic matter amendments to improve water retention.',
            ],
            [
                'name' => 'Clay',
                'soil_texture' => 'Fine',
                'water_retention' => 85.00,
                'drainage' => 10.00,
                'organic_matter' => 3.50,
                'fertility' => 'High',
                'salinity' => 5.00,
                'ph_min' => 6.5,
                'ph_max' => 8.0,
                'recommended_crops' => 'Rice, Wheat, Broccoli, Lettuce, Beans',
                'description' => 'Clay soil has very fine particles and retains large amounts of water. It drains poorly and can become compacted, but is rich in nutrients.',
                'notes' => 'Prone to waterlogging. Add gypsum or organic matter to improve structure. Avoid working when wet.',
            ],
            [
                'name' => 'Loamy',
                'soil_texture' => 'Medium',
                'water_retention' => 60.00,
                'drainage' => 60.00,
                'organic_matter' => 4.00,
                'fertility' => 'High',
                'salinity' => 3.00,
                'ph_min' => 6.0,
                'ph_max' => 7.0,
                'recommended_crops' => 'Wheat, Corn, Tomato, Cotton, Sunflower, Potato, Grapes',
                'description' => 'Loamy soil is a balanced mix of sand, silt and clay. It offers good water retention and drainage, making it ideal for most crops.',
                'notes' => 'Considered the ideal agricultural soil. Maintains good structure and supports diverse crop production.',
            ],
            [
                'name' => 'Silty',
                'soil_texture' => 'Medium-Fine',
                'water_retention' => 70.00,
                'drainage' => 45.00,
                'organic_matter' => 3.80,
                'fertility' => 'Medium-High',
                'salinity' => 3.50,
                'ph_min' => 6.0,
                'ph_max' => 7.0,
                'recommended_crops' => 'Wheat, Corn, Tomato, Sunflower, Rice',
                'description' => 'Silty soil has medium-sized particles and holds moisture well. It is fertile and drains moderately, suitable for a wide range of crops.',
                'notes' => 'Can compact easily. Avoid excessive tillage. Benefits from cover cropping to maintain structure.',
            ],
            [
                'name' => 'Peaty',
                'soil_texture' => 'Fibrous',
                'water_retention' => 80.00,
                'drainage' => 30.00,
                'organic_matter' => 25.00,
                'fertility' => 'Medium',
                'salinity' => 1.50,
                'ph_min' => 3.5,
                'ph_max' => 5.5,
                'recommended_crops' => 'Blueberry, Cranberry, Potato, Spinach, Lettuce',
                'description' => 'Peaty soil is dark, rich in organic matter and retains a lot of water. It is slightly acidic and works well for water-loving crops.',
                'notes' => 'Requires lime application to raise pH for most crops. Excellent water-holding capacity but needs drainage management.',
            ],
            [
                'name' => 'Chalky',
                'soil_texture' => 'Coarse-Medium',
                'water_retention' => 25.00,
                'drainage' => 80.00,
                'organic_matter' => 2.00,
                'fertility' => 'Medium',
                'salinity' => 4.00,
                'ph_min' => 7.0,
                'ph_max' => 8.5,
                'recommended_crops' => 'Olive, Grapes, Barley, Lavender, Thyme',
                'description' => 'Chalky soil is alkaline and stony. It drains quickly and retains little water, but supports drought-tolerant crops well.',
                'notes' => 'Often overlies limestone. May cause iron deficiency (chlorosis) in acid-loving plants. Add organic matter to improve.',
            ],
            [
                'name' => 'Saline',
                'soil_texture' => 'Variable',
                'water_retention' => 40.00,
                'drainage' => 50.00,
                'organic_matter' => 2.00,
                'fertility' => 'Low',
                'salinity' => 15.00,
                'ph_min' => 7.0,
                'ph_max' => 8.5,
                'recommended_crops' => 'Barley, Cotton, Sugar Beet, Date Palm, Alfalfa',
                'description' => 'Saline soil has high salt content which can inhibit plant growth. Only salt-tolerant crops thrive in this soil type.',
                'notes' => 'Requires leaching with fresh water to reduce salt concentration. Install drainage systems to flush salts below root zone.',
            ],
            [
                'name' => 'Sandy Loam',
                'soil_texture' => 'Sandy-Medium',
                'water_retention' => 35.00,
                'drainage' => 75.00,
                'organic_matter' => 2.50,
                'fertility' => 'Medium',
                'salinity' => 2.50,
                'ph_min' => 5.8,
                'ph_max' => 7.0,
                'recommended_crops' => 'Potato, Corn, Tomato, Grapes, Carrot, Peanut, Sunflower, Barley',
                'description' => 'Sandy loam is mostly sand with a small amount of clay and silt. It drains well while retaining just enough moisture for root crops and vegetables.',
                'notes' => 'Excellent for root vegetables and tubers. Warms up quickly in spring, allowing early planting.',
            ],
            [
                'name' => 'Clay Loam',
                'soil_texture' => 'Medium-Heavy',
                'water_retention' => 72.00,
                'drainage' => 35.00,
                'organic_matter' => 3.80,
                'fertility' => 'High',
                'salinity' => 4.50,
                'ph_min' => 6.2,
                'ph_max' => 7.5,
                'recommended_crops' => 'Wheat, Rice, Cotton, Corn, Broccoli, Beans',
                'description' => 'Clay loam has a higher clay content than loam, providing better water retention at the cost of drainage. Good for grain crops.',
                'notes' => 'Requires careful irrigation management to avoid waterlogging. Add organic matter to improve drainage and structure.',
            ],
            [
                'name' => 'Silty Clay',
                'soil_texture' => 'Fine-Heavy',
                'water_retention' => 78.00,
                'drainage' => 20.00,
                'organic_matter' => 4.20,
                'fertility' => 'High',
                'salinity' => 5.50,
                'ph_min' => 6.0,
                'ph_max' => 7.5,
                'recommended_crops' => 'Rice, Wheat, Soybean, Beans, Lettuce',
                'description' => 'Silty clay is dense, retains water very well but drains slowly. It is fertile but prone to waterlogging if irrigation is not managed carefully.',
                'notes' => 'Requires raised beds or drainage systems in wet climates. Very fertile when properly managed. Not suitable for shallow-rooted crops without drainage.',
            ],
        ];

        foreach ($soils as $soil) {
            Soil::create($soil);
        }
    }
}
